// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOnKtnqJX5P-uOClu8AdO4JjABxhhkey8',
    appId: '1:43333663866:web:79175038bf3414ba664fc3',
    messagingSenderId: '43333663866',
    projectId: 'e-shop-d10f9',
    authDomain: 'e-shop-d10f9.firebaseapp.com',
    storageBucket: 'e-shop-d10f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYtkkRal8lgxWe0RTdnKRgYsjJUXZtBEw',
    appId: '1:43333663866:android:8fe4d13e2a5c6665664fc3',
    messagingSenderId: '43333663866',
    projectId: 'e-shop-d10f9',
    storageBucket: 'e-shop-d10f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuIdigDF7FbZNB263oBHaIXrJ_Ktiu6lA',
    appId: '1:43333663866:ios:35759f9b22d8b5ee664fc3',
    messagingSenderId: '43333663866',
    projectId: 'e-shop-d10f9',
    storageBucket: 'e-shop-d10f9.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuIdigDF7FbZNB263oBHaIXrJ_Ktiu6lA',
    appId: '1:43333663866:ios:35759f9b22d8b5ee664fc3',
    messagingSenderId: '43333663866',
    projectId: 'e-shop-d10f9',
    storageBucket: 'e-shop-d10f9.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOnKtnqJX5P-uOClu8AdO4JjABxhhkey8',
    appId: '1:43333663866:web:aef1bcbc3f150d69664fc3',
    messagingSenderId: '43333663866',
    projectId: 'e-shop-d10f9',
    authDomain: 'e-shop-d10f9.firebaseapp.com',
    storageBucket: 'e-shop-d10f9.appspot.com',
  );
}
